import os
import re

def read_devnagri_text(text):
    text = text.replace('\u200c', '')
    text = text.replace('\u200d', '')
    text = text.replace('\ufeff', '')
    text = text.replace('\xad', '')
    text = text.replace(u'-','')
    text = text.replace('-','')
    text = text.replace('–','')
    text = text.replace('—','')
    text = text.replace(' : ','')
    text = text.replace('’','')
    text = text.replace('“','')
    text = text.replace('”','')
    text = text.replace('!','')
    text = text.replace('%','')
    text = text.replace('&','')
    text = text.replace('*','')
    text = text.replace('+','')
    text = text.replace('?','')
    text = text.replace('/','')
    text = text.replace(';','')
    text = text.replace('{','')
    text = text.replace('}','')
    text = text.replace('=','')
    text = text.replace(',','')
    text = text.replace('\'','')
    text = text.replace('"','')
    text = text.replace(u'.','')
    text = text.replace('॥','')
    text = text.replace(')','')
    text = text.replace('(','')
    text = text.replace('[','')
    text = text.replace(']','')
    text = text.replace('<','')
    text = text.replace('>','')
    text = text.replace('`','')
    text = text.replace('‘','')
    text = text.replace('#','')
    text = text.replace('।', '')
    text = text.replace('|', '')
    text = re.sub('[0-9a-zA-Z]', '', text)
    text = re.sub('[०-९]', '', text)
    text = text.strip()
    return text
